### ISSUE TITLE
Convite para Organização

### ISSUE THREAD

**Issue by caue-alves** [RodrigoPiropo/RodrigoPiropo#1]
Olá @RodrigoPiropo, eu e meu amigo @Felipe-Souza-Pereira-Lima estamos criando um projeto chamado [Dsa-Terminal](https://github.com/Dsa-Terminal/Dsa-Terminal), um simulador de Bash GNU/Linux feito em Python. Como você sabe bastante de Python e nós estamos precisando de contribuidores,  gostaria de te convidar para entrar em nossa organização, situação onde todos ganharíamos com uma equipe maior e mais amadurecimentos com um projeto prático. Caso aceite, irei te mandar um convite para as organizações @Dsa-Software e @Dsa-Terminal.

**Comment by RodrigoPiropo** [comment]
Olá @caue-alves achei um projeto incrível e bem corajoso, irei rodar na minha máquina e qualquer problema eu reporto; se esse estiver contido nos poucos arquivos python eu até ajudo, porém, não estarei podendo contribuir ativamente com o time devido ao meu tempo insuficiente. Obrigado pelo convite!

**Comment by caue-alves** [comment]
Olá @RodrigoPiropo, entendo, qualquer ajuda, mesmo que mínima é bem vinda, entendo sua questão de tempo, mas mesmo assim, muito obrigado por responder.
